[tool.poetry]
name = "apparent"
version = "0.1.0"
description = "Analyzing Physician-Patient Referral Networks"
authors = ["jeremy.wayland <jeremy.don.wayland@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "apparent"}]

[tool.poetry.dependencies]
python = "^3.10"
curvature-filtrations = "^0.1.0"
pandas = "^2.2.3"
python-dotenv = "^1.0.1"
matplotlib = "^3.9.2"
tqdm = "^4.67.1"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.3"

[tool.black]
line-length = 79

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
